#base.url
base.url=https://eservices.rs.ge/Login.aspx

#userdata
user.name=Tbilisi
user.password=123456

#applicationForm700
from.month=2
from.year=2026
to.month=7
to.year=2026

#apiBaseUrl
api.base.url=https://eservices.rs.ge/Login.aspx

#fillBuyerTin
buyer.tin=12345678910

#addProduct
product.name=testProduct
unit=ცალი
quantity=2
amount.vat=2000

wait=30
